### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by prtkjakhar** [SamagraX-Stencil/ui-templates#14]

**Comment by biratdatta** [comment]
- [ ] Create Navbar with these elements
1. Brand Name
2. Hamburger Menu
3. Logo
4. Home Button
5. Write the Test to test the component
- [ ] Create a JSON File to reflect changes on the UI
- [ ] Add config and render it in admin
- [ ] Create a Bot JSON File to take UI changes from the user that will be passed to the template JSON
- [ ] Document
