### ISSUE TITLE
Create Registration Molecule

### ISSUE THREAD

**Issue by prtkjakhar** [SamagraX-Stencil/ui-templates#7]
### SS:
![Register](https://github.com/SamagraX-Stencil/ui-templates/assets/65057795/e010e58d-cf2b-44d9-be55-1378d08a557b)
![Register - citizen](https://github.com/SamagraX-Stencil/ui-templates/assets/65057795/8d02f1f8-8a75-4bc4-8003-0dae31907090)

**Comment by Apoorvgarg-creator** [comment]
Hi I saw this issue requires some test cases!  Can I take this issue ?

**Comment by MohitNSamagra** [comment]
Hey
