### ISSUE TITLE
Enhancement : Image is missing or not loading

### ISSUE THREAD

**Issue by ankitmlesmagico** [SamagraX-Stencil/ui-templates#70]
![image](https://github.com/SamagraX-Stencil/ui-templates/assets/148052751/dbf89dd8-5ec9-4991-a58a-ab4a57324d7a)

https://stencil-ui-templates.vercel.app/downtime-page (downtime page image is missing)
- [ ] correct the missing image issue

**Comment by soumya-maheshwari** [comment]
Hi @ankitmlesmagico,

I've submitted a pull request #100  to address the missing image issue on the downtime page. Could you please take a moment to review it?

Thank you!
