### ISSUE TITLE
Enhancement : space between feedback box and submit button

### ISSUE THREAD

**Issue by ankitmlesmagico** [SamagraX-Stencil/ui-templates#71]
![image](https://github.com/SamagraX-Stencil/ui-templates/assets/148052751/9426e02a-8a50-4047-a5a6-0b6b55c4a4bf)

On Feedback page (https://stencil-ui-templates.vercel.app/feedback-page) space between feedback box and the button is not correct.

- [ ] Corrected space between feedback box and button

**Comment by ma1hotraz** [comment]
@ankitmlesmagico , i have corrected the space bw feedback box and button here - #97
