### ISSUE TITLE
Enhancement : Button space is too wide

### ISSUE THREAD

**Issue by ankitmlesmagico** [SamagraX-Stencil/ui-templates#73]
![image](https://github.com/SamagraX-Stencil/ui-templates/assets/148052751/67a45be1-5d33-4721-9398-da0481ff8301)

On DownTime page(https://stencil-ui-templates.vercel.app/downtime-page) in case of mobile phone button space is too  wide

- [ ] reduce the space between the two button

**Comment by harshilshah99** [comment]
@ankitmlesmagico I have made PR for the above issue, kindly review it
