### ISSUE TITLE
Enhancement : Margin is missing around text

### ISSUE THREAD

**Issue by ankitmlesmagico** [SamagraX-Stencil/ui-templates#74]
![image](https://github.com/SamagraX-Stencil/ui-templates/assets/148052751/9006f22f-01a8-419d-bad7-e70a8117a4f3)

On Launch Page (https://stencil-ui-templates.vercel.app/launch-page ) in mobile margin around the text is not correct.

- [ ] Add margin around the text

**Comment by niteshtiwari52** [comment]
I make a PR #101 
could you please review it.
