### ISSUE TITLE
Enhancement : Unwanted white space in the bottom of the navigation menu

### ISSUE THREAD

**Issue by ankitmlesmagico** [SamagraX-Stencil/ui-templates#75]
![image](https://github.com/SamagraX-Stencil/ui-templates/assets/148052751/a9f78edd-cbf2-414d-8d56-0ba123a6b937)

In case of mobile navigation menu is scrollable with extra white space at botton.

- [x] correct the extra white space issue

**Comment by ma1hotraz** [comment]
@ankitmlesmagico i have fixed this issue and raised a PR too. Please assign me this issue.

**Comment by ma1hotraz** [comment]
@ankitmlesmagico I have many raised PRs against a few issues. Please have a look and assign those to me.

**Comment by ma1hotraz** [comment]
@prtkjakhar done! 
That build issue was caused do to overriding if the types. I asked kavikumar to fixed it. Now he has fixed it..
