### ISSUE TITLE
Enhancement : default rating

### ISSUE THREAD

**Issue by ankitmlesmagico** [SamagraX-Stencil/ui-templates#76]
![image](https://github.com/SamagraX-Stencil/ui-templates/assets/148052751/65bfbcab-6a04-4951-a45c-39f307c2df84)

default rating should be not 1 is should be not selected

- [ ] make default rating to 0 and make is compulsory

**Comment by ma1hotraz** [comment]
@ankitmlesmagico I have fixed this issue and created a PR for the same. Please assign it to me.
