### ISSUE TITLE
Enhancement : border should appear on correct delete icon

### ISSUE THREAD

**Issue by ankitmlesmagico** [SamagraX-Stencil/ui-templates#77]
![image](https://github.com/SamagraX-Stencil/ui-templates/assets/148052751/b0ef59bb-760c-4fcf-bdbc-bbb27272305e)

in history page (https://stencil-ui-templates.vercel.app/history-page) when i click on second delete icon border is appear on the first icon

- [ ] correct the highlight and border part while delete the history

**Comment by Abro0058T** [comment]
@ankitmlesmagico  I guess this issue is not in there any more. But after we delete the conversation the border automatically get applied on  the adjacent conversation . Should is remove this bug  ?

**Comment by thekavikumar** [comment]
@ankitmlesmagico i guess the issue is resolved. there seems to no bug
