### ISSUE TITLE
Enhancement : color of navigation menu should be match

### ISSUE THREAD

**Issue by ankitmlesmagico** [SamagraX-Stencil/ui-templates#78]
![image](https://github.com/SamagraX-Stencil/ui-templates/assets/148052751/77ba1720-2f26-4238-afe7-222fd3f5af2d)

On Molecule page when we click on the navigation bar as shown in above image

![image](https://github.com/SamagraX-Stencil/ui-templates/assets/148052751/d2ca8a47-e4e1-40bb-b5c6-d2e69e1bce80)
color of the navigation menu is comming as white 

- [ ] both top bar and left navigation menu color should be match

**Comment by Sayan2908** [comment]
@ankitmlesmagico I have changed the color of the menu
Please review the code and mention if any changes necessary
![Screenshot 2024-04-23 171626](https://github.com/SamagraX-Stencil/ui-templates/assets/107147382/fe1e3daa-03f8-4a56-ba29-a36aab5d868e)
