### ISSUE TITLE
Enhancement : border should move while typing otp

### ISSUE THREAD

**Issue by ankitmlesmagico** [SamagraX-Stencil/ui-templates#79]
![image](https://github.com/SamagraX-Stencil/ui-templates/assets/148052751/d30475ce-99b8-4395-9672-04dcffacf52c)

On OTP page (https://stencil-ui-templates.vercel.app/otp-page) the border around the otp box should move as we type number into the input box

- [ ] Border should not stay on one place

**Comment by harshilshah99** [comment]
@ankitmlesmagico I have made PR for the above issue, kindly review it
